# AUTOGENERATED! DO NOT EDIT! File to edit: 02_cli.ipynb (unless otherwise specified).

__all__ = ['in_notebook']

# Cell
from .core import *
import argparse
#import sys

# Cell
def in_notebook():
    "Returns True if run in a notebook environment."
    try:
        from IPython import get_ipython
        if 'IPKernelApp' not in get_ipython().config:
            return False
    except:
        return False
    return True

# Cell
if __name__ == '__main__' and not in_notebook():
    args = parse_arguments()