# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"show_cv2": "00_core.ipynb",
         "blur": "00_core.ipynb",
         "pixelate": "00_core.ipynb",
         "find_faces": "00_core.ipynb",
         "blur_areas": "00_core.ipynb",
         "anonymize": "00_core.ipynb",
         "load_img": "00_core.ipynb",
         "in_notebook": "02_cli.ipynb",
         "uploaded_file": "03_streamlit.ipynb"}

modules = ["core.py",
           "__main__.py",
           "streamlit.py"]

doc_url = "https://JohannesStutz.github.io/blurry/"

git_url = "https://github.com/JohannesStutz/blurry/tree/master/"

def custom_doc_links(name): return None
